# Multi-Service Mode: HTTP APIs for Resume Generation
services:
  # Resume Generation API Service
  resume-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    networks:
      - internal
    depends_on:
      - pdf-service
    environment:
      - PDF_SERVICE_URL=http://pdf-service:3000

  # PDF Generation Service
  pdf-service:
    build:
      context: .
      dockerfile: Dockerfile.pdf-service
    networks:
      - internal
    cap_add:
      - SYS_ADMIN # Required for Chromium
    security_opt:
      - seccomp:unconfined

networks:
  internal:
    driver: bridge
